/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Car;
import model.CarCatalog;
/**
 *
 * @author niulp
 */
public class SearchPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchPanel
     */
    CarCatalog cars;
    
    public SearchPanel(CarCatalog cars) {
        initComponents();
        this.cars = cars;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSearchModel = new javax.swing.JLabel();
        lblSearchSerialNumber = new javax.swing.JLabel();
        lblSearchLocation = new javax.swing.JLabel();
        lblSearchAvailable = new javax.swing.JLabel();
        txtSearchModel = new javax.swing.JTextField();
        txtSearchSerialNumber = new javax.swing.JTextField();
        txtSearchLocation = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSearchModel = new javax.swing.JButton();
        btnSearchSerialNumber = new javax.swing.JButton();
        btnSearchLocation = new javax.swing.JButton();
        btnSearchAvailable = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSearchedCars = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtSearchMinSeats = new javax.swing.JTextField();
        txtSearchMaxSeats = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSearchBySeatCount = new javax.swing.JButton();
        checkBoxSearchIsAvailable = new javax.swing.JCheckBox();
        lblSearchCertificateExpired = new javax.swing.JLabel();
        checkBoxSearchExpiredCertifiicate = new javax.swing.JCheckBox();
        btnSearchExpiredCertificate = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtSearchCarbrand = new javax.swing.JTextField();
        btnSearchCarBrand = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblSearchModel.setForeground(new java.awt.Color(102, 0, 153));
        lblSearchModel.setText("Model :");

        lblSearchSerialNumber.setForeground(new java.awt.Color(102, 0, 153));
        lblSearchSerialNumber.setText("Serial Number : ");

        lblSearchLocation.setForeground(new java.awt.Color(102, 0, 153));
        lblSearchLocation.setText("Location : ");

        lblSearchAvailable.setForeground(new java.awt.Color(102, 0, 153));
        lblSearchAvailable.setText("Available : ");

        txtSearchModel.setText(" ");

        txtSearchSerialNumber.setText(" ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SEARCH");

        btnSearchModel.setForeground(new java.awt.Color(102, 0, 153));
        btnSearchModel.setText("Apply");
        btnSearchModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchModelActionPerformed(evt);
            }
        });

        btnSearchSerialNumber.setForeground(new java.awt.Color(102, 0, 153));
        btnSearchSerialNumber.setText("Apply");
        btnSearchSerialNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchSerialNumberActionPerformed(evt);
            }
        });

        btnSearchLocation.setForeground(new java.awt.Color(102, 0, 153));
        btnSearchLocation.setText("Apply");
        btnSearchLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchLocationActionPerformed(evt);
            }
        });

        btnSearchAvailable.setForeground(new java.awt.Color(102, 0, 153));
        btnSearchAvailable.setText("Apply");
        btnSearchAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchAvailableActionPerformed(evt);
            }
        });

        tblSearchedCars.setForeground(new java.awt.Color(102, 0, 153));
        tblSearchedCars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Model", "Serial Number", "Location", "Seats", "Added timestamp", "Updated timestamp", "Manufactured year", "Car brand"
            }
        ));
        jScrollPane1.setViewportView(tblSearchedCars);

        jLabel2.setForeground(new java.awt.Color(102, 0, 153));
        jLabel2.setText("Seats : ");

        txtSearchMinSeats.setText(" ");

        txtSearchMaxSeats.setText(" ");

        jLabel3.setText("-");

        jLabel4.setText("min");

        jLabel5.setText("max ");

        btnSearchBySeatCount.setForeground(new java.awt.Color(102, 0, 153));
        btnSearchBySeatCount.setText("Apply");
        btnSearchBySeatCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBySeatCountActionPerformed(evt);
            }
        });

        checkBoxSearchIsAvailable.setForeground(new java.awt.Color(102, 0, 153));
        checkBoxSearchIsAvailable.setText(" Yes");

        lblSearchCertificateExpired.setForeground(new java.awt.Color(102, 0, 153));
        lblSearchCertificateExpired.setText("Certificate expired :");

        checkBoxSearchExpiredCertifiicate.setForeground(new java.awt.Color(102, 0, 153));
        checkBoxSearchExpiredCertifiicate.setText("Yes");

        btnSearchExpiredCertificate.setForeground(new java.awt.Color(102, 0, 153));
        btnSearchExpiredCertificate.setText("Apply");
        btnSearchExpiredCertificate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchExpiredCertificateActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(102, 0, 153));
        jLabel6.setText("Car brand : ");

        txtSearchCarbrand.setText(" ");

        btnSearchCarBrand.setForeground(new java.awt.Color(102, 0, 153));
        btnSearchCarBrand.setText("Apply");
        btnSearchCarBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCarBrandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSearchModel)
                            .addComponent(lblSearchLocation)
                            .addComponent(lblSearchSerialNumber)
                            .addComponent(lblSearchAvailable))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtSearchModel, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                .addComponent(txtSearchSerialNumber)
                                .addComponent(txtSearchLocation))
                            .addComponent(checkBoxSearchIsAvailable))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSearchAvailable)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSearchModel)
                                    .addComponent(btnSearchSerialNumber)
                                    .addComponent(btnSearchLocation))
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4)
                                        .addGap(17, 17, 17)
                                        .addComponent(txtSearchMinSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSearchMaxSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnSearchBySeatCount))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(lblSearchCertificateExpired))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(checkBoxSearchExpiredCertifiicate)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnSearchExpiredCertificate))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtSearchCarbrand, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(29, 29, 29)
                                                .addComponent(btnSearchCarBrand))))))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearchModel)
                    .addComponent(txtSearchModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchModel)
                    .addComponent(jLabel2)
                    .addComponent(txtSearchMinSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchMaxSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(btnSearchBySeatCount))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSearchSerialNumber)
                            .addComponent(txtSearchSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchSerialNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSearchLocation)
                            .addComponent(txtSearchLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchLocation)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSearchCertificateExpired)
                            .addComponent(checkBoxSearchExpiredCertifiicate)
                            .addComponent(btnSearchExpiredCertificate))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSearchAvailable)
                            .addComponent(btnSearchAvailable)
                            .addComponent(checkBoxSearchIsAvailable)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtSearchCarbrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchCarBrand))))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(290, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchModelActionPerformed
        // TODO add your handling code here:
        String searchedModel = txtSearchModel.getText();
        List<Car> carsFilteredByModel = cars.findCarByModel(searchedModel);
        populateSearchedCars(carsFilteredByModel);
    }//GEN-LAST:event_btnSearchModelActionPerformed

    private void btnSearchSerialNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchSerialNumberActionPerformed
        // TODO add your handling code here:
        String searchedSerialNumber = txtSearchSerialNumber.getText();
        List<Car> carsFilteredBySerialNumber = cars.findCarBySerialNumber(searchedSerialNumber);
        populateSearchedCars(carsFilteredBySerialNumber);
    }//GEN-LAST:event_btnSearchSerialNumberActionPerformed

    private void btnSearchLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchLocationActionPerformed
        // TODO add your handling code here:
        String searchedLocation = txtSearchLocation.getText();
        List<Car> carsFilteredByLocation = cars.findCarByLocation(searchedLocation);
        populateSearchedCars(carsFilteredByLocation);
    }//GEN-LAST:event_btnSearchLocationActionPerformed

    private void btnSearchAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAvailableActionPerformed
        // TODO add your handling code here:
        Boolean isAvailable = checkBoxSearchIsAvailable.isSelected();
        List<Car> searchedCars = cars.findCarByAvailability(isAvailable);
        populateSearchedCars(searchedCars);
    }//GEN-LAST:event_btnSearchAvailableActionPerformed

    private void btnSearchBySeatCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBySeatCountActionPerformed
        // TODO add your handling code here:
        int minSeats = Integer.parseInt(txtSearchMinSeats.getText());
        int maxSeats = Integer.parseInt(txtSearchMaxSeats.getText());
        List<Car> carsFilteredBySeatCount = cars.findCarBySeatCount(minSeats, maxSeats);
        populateSearchedCars(carsFilteredBySeatCount);
    }//GEN-LAST:event_btnSearchBySeatCountActionPerformed

    private void btnSearchExpiredCertificateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchExpiredCertificateActionPerformed
        // TODO add your handling code here:
        Boolean isExpiredCertificate = checkBoxSearchExpiredCertifiicate.isSelected();
        List<Car> searchedCars = cars.findCarByExpiredCertificate(isExpiredCertificate);
        populateSearchedCars(searchedCars);
    }//GEN-LAST:event_btnSearchExpiredCertificateActionPerformed

    private void btnSearchCarBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCarBrandActionPerformed
        // TODO add your handling code here:
        String searchedCarBrand = txtSearchCarbrand.getText();
        List<Car> carsFilteredByCarbrand = cars.findCarByCarBrand(searchedCarBrand);
        populateSearchedCars(carsFilteredByCarbrand);
    }//GEN-LAST:event_btnSearchCarBrandActionPerformed

    private void populateSearchedCars(List<Car> searchedCars) {
        DefaultTableModel model = (DefaultTableModel) tblSearchedCars.getModel();
        model.setRowCount(0);
        for (Car cs : searchedCars) {
            Object[] row = new Object[8];
            row[0] = cs;
            row[1] = cs.getSerialNumber();
            row[2] = cs.getLocation();
            row[3] = cs.getSeats();
            row[4] = cs.getTimestampAdded();
            row[5] = cs.getTimestampUpdated();
            row[6] = cs.getManufacturedYear();
            row[7] = cs.getCarBrand();
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearchAvailable;
    private javax.swing.JButton btnSearchBySeatCount;
    private javax.swing.JButton btnSearchCarBrand;
    private javax.swing.JButton btnSearchExpiredCertificate;
    private javax.swing.JButton btnSearchLocation;
    private javax.swing.JButton btnSearchModel;
    private javax.swing.JButton btnSearchSerialNumber;
    private javax.swing.JCheckBox checkBoxSearchExpiredCertifiicate;
    private javax.swing.JCheckBox checkBoxSearchIsAvailable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSearchAvailable;
    private javax.swing.JLabel lblSearchCertificateExpired;
    private javax.swing.JLabel lblSearchLocation;
    private javax.swing.JLabel lblSearchModel;
    private javax.swing.JLabel lblSearchSerialNumber;
    private javax.swing.JTable tblSearchedCars;
    private javax.swing.JTextField txtSearchCarbrand;
    private javax.swing.JTextField txtSearchLocation;
    private javax.swing.JTextField txtSearchMaxSeats;
    private javax.swing.JTextField txtSearchMinSeats;
    private javax.swing.JTextField txtSearchModel;
    private javax.swing.JTextField txtSearchSerialNumber;
    // End of variables declaration//GEN-END:variables
}
